<div class="footer_space" style="width:100%; height:10px;" ></div>
</div> 

<!-- footer --> 
<footer>
    <div class="container-fluid" style="padding-top:0px;">
        <div class="row-fluid">
            <div class="span12">
                <div style="width:400px; float:left;">&copy; <?php echo $site_name; ?> <?php echo date("Y"); ?></div>
				<div style="width:500px; float:left;">PDF is autogenerated at <?php echo date("d M, Y - h:i:s a"); ?> (GMT) <strong><a href="http://www.enrichelife.com" target="_blank">By Enrich</a></strong></div>
            </div>
        </div>
    </div>
</footer>